name: Setup Ubuntu Environment
description: Setup the pipeline environment for a given job

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Dependencies
      id: prep
      shell: bash
      run: |
        python -m pip install -q --upgrade pip pipenv
        pipenv install -d
        pipenv graph
    - name: Setup Environment Variables
      id: env
      shell: bash
      run: |
        echo "PACKAGE_NAME=splogin" >> $GITHUB_ENV
        echo $GITHUB_ENV
