##
#   Copyright (c) 2024 Valentin Weber
#
#   This file is part of the software playlisttion.
#
#   The software is licensed under the European Union Public License
#   (EUPL) version 1.2 or later. You should have received a copy of
#   the english license text with the software. For your rights and
#   obligations under this license refer to the file LICENSE or visit
#   https://joinup.ec.europa.eu/community/eupl/og_page/eupl to view
#   official translations of the licence in another language of the EU.
##

name: checks

on:
  push:
    tags:
      - v*
    branches:
      - "*"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: Setup Job
        uses: ./.github/actions/setup-ubuntu
      - name: Run Bandit Security Checks
        id: security
        continue-on-error: true
        run: |
          pipenv run bandit -r $PACKAGE_NAME
      - name: Run pydocstyle Checks
        id: pydocstyle
        continue-on-error: true
        run: pipenv run pydocstyle $PACKAGE_NAME
      - name: Run Flake8
        id: flake8
        continue-on-error: true
        run : pipenv run flake8 --doctests --max-doc-length 72 $PACKAGE_NAME
      - name: Run Pylint
        continue-on-error: true
        id: pylint
        run: pipenv run pylint -f colorized $PACKAGE_NAME || pipenv run pylint-exit -efail -wfail $?
      # - name: Build Source Distribution
      #   id: build
      #   run: |
      #     name=$(python --name)
      #     version=$(python --version)
      #     echo "::set-output name=name::${name}"
      #     echo "::set-output name=sdist::${name}-${version}.tar.gz"
      #     echo "::set-output name=bdist::$PACKAGE_NAME-${version}-py3-none-any.whl"
      #     python sdist
      # - name: Create Release  # only on tags starting with v
      #   if: ${{ startsWith( github.ref, 'refs/tags/v' ) }}
      #   id: release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ steps.build.outputs.name }} ${{ github.ref }}
      # - name: Upload Source Distribution  # only on tags starting with v
      #   if: ${{ startsWith( github.ref, 'refs/tags/v' ) }}
      #   id: upload_sdist
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.release.outputs.upload_url }}
      #     asset_path: ./dist/${{ steps.build.outputs.sdist }}
      #     asset_name: ${{ steps.build.outputs.name }}.tar.gz
      #     asset_content_type: application/x-gzip
      # - name: Publish PyPI  # only on tags starting with v
      #   if: ${{ startsWith( github.ref, 'refs/tags/v' ) }}
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_TOKEN }}
